version: "3.8"
services:
  mongo:
    image: mongo:3.6.18-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./TestUserDb:/docker-entrypoint-initdb.d  
      - ./dbscripts:/dbscripts
    container_name: training_mongo
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - mongo
    container_name: training_mongo_express
  trainingapicore:
    build:
        context: .
        dockerfile: Dockerfile
    environment: 
        ASPNETCORE_ENVIRONMENT: Development
    image: training-api
    restart: on-failure
    ports:
      - 44327:80
    container_name: training_api