name: RunTests
on: 
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  unit_tests:
      name: dotnet-tests-report
      runs-on: ubuntu-latest
      steps:
        - uses: zyborg/dotnet-tests-report@v1.3.0
          with:
            msbuild_verbosity: 'n'
            set_check_status_from_test_outcome: true
            project_path: Training.API.Core.Tests
            report_name: unit_tests
            report_title: Unit Tests
            github_token: ${{ secrets.GITHUB_TOKEN }}  
